FROM node:lts-alpine3.16

# Path: dockerFile
WORKDIR /app

COPY package*.json .
COPY pnpm-lock.yaml .

RUN npm install -g pnpm

COPY . .
EXPOSE 3000

ENV VITE_APP_NAME="Clases de Programacion"
ENV BASE_URL=''

CMD ["pnpm", "dev"]