const {
	VITE_APP_FIREBASE_API_KEY,
	VITE_APP_FIREBASE_APP_ID,
	VITE_APP_FIREBASE_AUTH_DOMAIN,
	VITE_APP_FIREBASE_MEASUREMENT_ID,
	VITE_APP_FIREBASE_MESSAGIN_SENDER_ID,
	VITE_APP_FIREBASE_PROJECT_ID,
	VITE_APP_FIREBASE_SORAGE_BUCKET,
	VITE_APP_NAME,
	BASE_URL,
	VITE_MESSAGING_EMAIL_URL,
} = import.meta.env;

export const AppConfig = {
	appName: VITE_APP_NAME,
	appUrl: BASE_URL,
};

export const firebaseConfig = {
	apiKey: VITE_APP_FIREBASE_API_KEY,
	authDomain: VITE_APP_FIREBASE_AUTH_DOMAIN,
	projectId: VITE_APP_FIREBASE_PROJECT_ID,
	storageBucket: VITE_APP_FIREBASE_SORAGE_BUCKET,
	messaginSenderId: VITE_APP_FIREBASE_MESSAGIN_SENDER_ID,
	appId: VITE_APP_FIREBASE_APP_ID,
	measurementId: VITE_APP_FIREBASE_MEASUREMENT_ID,
};

export const senderConfig = {
	emailSenderUrl: VITE_MESSAGING_EMAIL_URL,
};
